ALTER TABLE transactions ADD COLUMN type VARCHAR(10) NOT NULL DEFAULT 'TRANSFER';
ALTER TABLE transactions ALTER COLUMN source_wallet_id DROP NOT NULL;
ALTER TABLE transactions ALTER COLUMN type DROP DEFAULT;
